/** @file     SchM_PduR.h
  *
  * @brief    Basic Software Scheduler Module Interlink header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS GmbH  RTA-RTE v5.7.0  (R4.0 backend version: v7.4.9 (Build 39454))
  *           at Tue Mar 01 12:01:56 2016
  */

#ifndef SchM_PduR
#define SchM_PduR

#include "SchM_PduR_Type.h"
#include "Rte_Intl.h"
#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#if !defined(RTE_RUNNABLEAPI_BSWSE_Dummy1)
#define RTE_PRV_ALL_API
#endif

/* API Mapping Macros */
#ifndef RTE_CORE
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_BSWSE_Dummy1)
/* Inline function call optimization; SchM_Enter_PduR_LockDisableRoutingNoNest to direct access */
#define SchM_Enter_PduR_LockDisableRoutingNoNest()  ( GetResource(Rte_EA_BSWImpl7_BSWIMPL_PduR_LockDisableRoutingNoNest) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_BSWSE_Dummy1)
/* Inline function call optimization; SchM_Enter_PduR_LockEnableRoutingNoNest to direct access */
#define SchM_Enter_PduR_LockEnableRoutingNoNest()  ( GetResource(Rte_EA_BSWImpl7_BSWIMPL_PduR_LockEnableRoutingNoNest) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_BSWSE_Dummy1)
/* Inline function call optimization; SchM_Enter_PduR_LockIFGatewayTriggerTxConf to direct access */
#define SchM_Enter_PduR_LockIFGatewayTriggerTxConf()  ( GetResource(Rte_EA_BSWImpl7_BSWIMPL_PduR_LockIFGatewayTriggerTxConf) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_BSWSE_Dummy1)
/* Inline function call optimization; SchM_Enter_PduR_LockIFGatewayTriggerTxNoNest to direct access */
#define SchM_Enter_PduR_LockIFGatewayTriggerTxNoNest()  ( GetResource(Rte_EA_BSWImpl7_BSWIMPL_PduR_LockIFGatewayTriggerTxNoNest) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_BSWSE_Dummy1)
/* Inline function call optimization; SchM_Enter_PduR_LockIFGatewayTx to direct access */
#define SchM_Enter_PduR_LockIFGatewayTx()  ( GetResource(Rte_EA_BSWImpl7_BSWIMPL_PduR_LockIFGatewayTx) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_BSWSE_Dummy1)
/* Inline function call optimization; SchM_Enter_PduR_LockIFGatewayTxConf to direct access */
#define SchM_Enter_PduR_LockIFGatewayTxConf()  ( GetResource(Rte_EA_BSWImpl7_BSWIMPL_PduR_LockIFGatewayTxConf) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_BSWSE_Dummy1)
/* Inline function call optimization; SchM_Enter_PduR_LockMCTxConfNoNest to direct access */
#define SchM_Enter_PduR_LockMCTxConfNoNest()  ( GetResource(Rte_EA_BSWImpl7_BSWIMPL_PduR_LockMCTxConfNoNest) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_BSWSE_Dummy1)
/* Inline function call optimization; SchM_Enter_PduR_LockMcTpTxConf to direct access */
#define SchM_Enter_PduR_LockMcTpTxConf()  ( GetResource(Rte_EA_BSWImpl7_BSWIMPL_PduR_LockMcTpTxConf) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_BSWSE_Dummy1)
/* Inline function call optimization; SchM_Enter_PduR_LockMcTpTxCopyTxData to direct access */
#define SchM_Enter_PduR_LockMcTpTxCopyTxData()  ( GetResource(Rte_EA_BSWImpl7_BSWIMPL_PduR_LockMcTpTxCopyTxData) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_BSWSE_Dummy1)
/* Inline function call optimization; SchM_Enter_PduR_LockTpGateway to direct access */
#define SchM_Enter_PduR_LockTpGateway()  ( GetResource(Rte_EA_BSWImpl7_BSWIMPL_PduR_LockTpGateway) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_BSWSE_Dummy1)
/* Inline function call optimization; SchM_Enter_PduR_LockTpGatewayBuffer to direct access */
#define SchM_Enter_PduR_LockTpGatewayBuffer()  ( GetResource(Rte_EA_BSWImpl7_BSWIMPL_PduR_LockTpGatewayBuffer) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_BSWSE_Dummy1)
/* Inline function call optimization; SchM_Enter_PduR_LockTpGatewayCopyRxData to direct access */
#define SchM_Enter_PduR_LockTpGatewayCopyRxData()  ( GetResource(Rte_EA_BSWImpl7_BSWIMPL_PduR_LockTpGatewayCopyRxData) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_BSWSE_Dummy1)
/* Inline function call optimization; SchM_Enter_PduR_LockTpGatewayCopyTxDataNoNest to direct access */
#define SchM_Enter_PduR_LockTpGatewayCopyTxDataNoNest()  ( GetResource(Rte_EA_BSWImpl7_BSWIMPL_PduR_LockTpGatewayCopyTxDataNoNest) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_BSWSE_Dummy1)
/* Inline function call optimization; SchM_Exit_PduR_LockDisableRoutingNoNest to direct access */
#define SchM_Exit_PduR_LockDisableRoutingNoNest()  ( ReleaseResource(Rte_EA_BSWImpl7_BSWIMPL_PduR_LockDisableRoutingNoNest) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_BSWSE_Dummy1)
/* Inline function call optimization; SchM_Exit_PduR_LockEnableRoutingNoNest to direct access */
#define SchM_Exit_PduR_LockEnableRoutingNoNest()  ( ReleaseResource(Rte_EA_BSWImpl7_BSWIMPL_PduR_LockEnableRoutingNoNest) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_BSWSE_Dummy1)
/* Inline function call optimization; SchM_Exit_PduR_LockIFGatewayTriggerTxConf to direct access */
#define SchM_Exit_PduR_LockIFGatewayTriggerTxConf()  ( ReleaseResource(Rte_EA_BSWImpl7_BSWIMPL_PduR_LockIFGatewayTriggerTxConf) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_BSWSE_Dummy1)
/* Inline function call optimization; SchM_Exit_PduR_LockIFGatewayTriggerTxNoNest to direct access */
#define SchM_Exit_PduR_LockIFGatewayTriggerTxNoNest()  ( ReleaseResource(Rte_EA_BSWImpl7_BSWIMPL_PduR_LockIFGatewayTriggerTxNoNest) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_BSWSE_Dummy1)
/* Inline function call optimization; SchM_Exit_PduR_LockIFGatewayTx to direct access */
#define SchM_Exit_PduR_LockIFGatewayTx()  ( ReleaseResource(Rte_EA_BSWImpl7_BSWIMPL_PduR_LockIFGatewayTx) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_BSWSE_Dummy1)
/* Inline function call optimization; SchM_Exit_PduR_LockIFGatewayTxConf to direct access */
#define SchM_Exit_PduR_LockIFGatewayTxConf()  ( ReleaseResource(Rte_EA_BSWImpl7_BSWIMPL_PduR_LockIFGatewayTxConf) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_BSWSE_Dummy1)
/* Inline function call optimization; SchM_Exit_PduR_LockMCTxConfNoNest to direct access */
#define SchM_Exit_PduR_LockMCTxConfNoNest()  ( ReleaseResource(Rte_EA_BSWImpl7_BSWIMPL_PduR_LockMCTxConfNoNest) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_BSWSE_Dummy1)
/* Inline function call optimization; SchM_Exit_PduR_LockMcTpTxConf to direct access */
#define SchM_Exit_PduR_LockMcTpTxConf()  ( ReleaseResource(Rte_EA_BSWImpl7_BSWIMPL_PduR_LockMcTpTxConf) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_BSWSE_Dummy1)
/* Inline function call optimization; SchM_Exit_PduR_LockMcTpTxCopyTxData to direct access */
#define SchM_Exit_PduR_LockMcTpTxCopyTxData()  ( ReleaseResource(Rte_EA_BSWImpl7_BSWIMPL_PduR_LockMcTpTxCopyTxData) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_BSWSE_Dummy1)
/* Inline function call optimization; SchM_Exit_PduR_LockTpGateway to direct access */
#define SchM_Exit_PduR_LockTpGateway()  ( ReleaseResource(Rte_EA_BSWImpl7_BSWIMPL_PduR_LockTpGateway) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_BSWSE_Dummy1)
/* Inline function call optimization; SchM_Exit_PduR_LockTpGatewayBuffer to direct access */
#define SchM_Exit_PduR_LockTpGatewayBuffer()  ( ReleaseResource(Rte_EA_BSWImpl7_BSWIMPL_PduR_LockTpGatewayBuffer) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_BSWSE_Dummy1)
/* Inline function call optimization; SchM_Exit_PduR_LockTpGatewayCopyRxData to direct access */
#define SchM_Exit_PduR_LockTpGatewayCopyRxData()  ( ReleaseResource(Rte_EA_BSWImpl7_BSWIMPL_PduR_LockTpGatewayCopyRxData) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_BSWSE_Dummy1)
/* Inline function call optimization; SchM_Exit_PduR_LockTpGatewayCopyTxDataNoNest to direct access */
#define SchM_Exit_PduR_LockTpGatewayCopyTxDataNoNest()  ( ReleaseResource(Rte_EA_BSWImpl7_BSWIMPL_PduR_LockTpGatewayCopyTxDataNoNest) )
#endif

#endif /* RTE_CORE */

/*******************************************************
 ***
 *** Schedulable Entity Prototypes
 ***
 *******************************************************/


#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* SchM_PduR */
