/** @file     SchM_PduR_Type.h
  *
  * @brief    Basic Software Scheduler Module Interlink Types header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS GmbH  RTA-RTE v5.7.0  (R4.0 backend version: v7.4.9 (Build 39454))
  *           at Tue Mar 01 12:01:56 2016
  */

#ifndef SchM_PduR_Type
#define SchM_PduR_Type

#include "Rte_Type.h"
#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* BEGIN: BSW implementation specific types */
/* END: BSW implementation specific types */

/* BEGIN: BSW implementation specific definitions */
/* END: BSW implementation specific definitions */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* SchM_PduR_Type */
