Src_include_is_val_in_range := C:/PROGRA~1/Razorcat/TESSY_4.3/Examples/ISVALU~1 
Src_cppflags_is_val_in_range := 
#Src_cppflags_tgt_is_val_in_range :=
#Src_cflags_tgt_is_val_in_range :=
BUFFER_SIZE := 10240
COMM_BUFFER_INTEGRITY := false
COMM_CHECKSUM := false
COMM_FILE_COMPRESSION := false
COMPILER_INCLUDES := c:/PROGRA~1/razorcat/TESSY_4.3/bin
COMPILER_INSTALL_PATH := C:/PROGRA~1/Razorcat/Shared/1.3/msys32
ENABLE_EXCEPTIONS := true
ENDIANESS := -
EXEFILE_EXTENSION := .exe
OBJFILE_EXTENSION := .o
TARGET_INSTALL_PATH := c:/PROGRA~1/razorcat/TESSY_4.3/bin
TIMER_ENABLED := false
TIMER_FILE := C:/PROGRA~1/Razorcat/TESSY_4.3/sys/src/comm/TS_TIM~2.C
