#
# This file was generated by Tessy, do not edit!
#
RootFolder            := C:/Users/yusenlin/Projects/TESSY/yu/tessy
Project               := 1024
Module                := 1150
Mod_env_files         := C:/PROGRA~1/Razorcat/TESSY_4.3/sys/TEMPLA~1/make/TSA088~1.TPL C:/PROGRA~1/Razorcat/TESSY_4.3/sys/TEMPLA~1/tks/tks-gnu.tpl C:/PROGRA~1/Razorcat/TESSY_4.3/sys/src/comm/TS_TIM~2.C C:/PROGRA~1/Razorcat/TESSY_4.3/sys/compiler/TYPETA~1/TS_GCC~1.XML
Mod_src_files         :=  C:/PROGRA~1/Razorcat/TESSY_4.3/Examples/ISVALU~1/is_val_in_range.c
Mod_tgt_control       := C:/Users/yusenlin/Projects/TESSY/yu/tessy/work/00000401/00000402/0000047e/IDBBUI~1/TARGET~1.MAK
