#
# This file was generated by Tessy, do not edit!
#
Tgt_compiler := gcc
Tgt_cppflags :=
Tgt_preproc = gcc.exe  -E -DTESSY -o  
Tgt_includes :=
Tgt_typetable := "C:\PROGRA~1\Razorcat\TESSY_4.3\sys\compiler\typetables\ts_gcc_i386_typetable.xml"
