
/*
 ************************************************************************* 
 *                                                                       * 
 *                      ROBERT BOSCH GMBH                                * 
 *                          STUTTGART                                    * 
 *                                                                       * 
 *          Alle Rechte vorbehalten - All rights reserved                * 
 *                                                                       *
 *                  Generated by ICE 3.1.3                               * 
 ************************************************************************* 
*/
   
#ifndef _RBA_MEMDIAG_DAT_H
#define _RBA_MEMDIAG_DAT_H

#include "Std_Types.h"
    
    

extern uint16 rba_MemDiagExtd_nrLstReadSngErr;

extern uint16 rba_MemDiag_nrLstReadErr;

extern uint16 rba_MemDiag_nrLstWrErr;


extern boolean rba_MemDiag_flgInhbDiag;

#define GET_rba_MemDiag_flgInhbDiag (rba_MemDiag_flgInhbDiag)
#define SET_rba_MemDiag_flgInhbDiag (rba_MemDiag_flgInhbDiag=TRUE)
#define CLR_rba_MemDiag_flgInhbDiag (rba_MemDiag_flgInhbDiag=FALSE)
#define PUT_rba_MemDiag_flgInhbDiag(val) (rba_MemDiag_flgInhbDiag = ((val) ? TRUE : FALSE))
    

#endif /* _RBA_MEMDIAG_DAT_H */

