/*<BASDKey>
 **********************************************************************************************************************
 *
 * COPYRIGHT RESERVED, 2010 Robert Bosch GmbH. All rights reserved.
 * The reproduction, distribution and utilization of this document as well as the communication of its contents to
 * others without explicit authorization is prohibited. Offenders will be held liable for the payment of damages.
 * All rights reserved in the event of the grant of a patent, utility model or design.
 *
 **********************************************************************************************************************
 * Administrative Information (automatically filled in)
 * $Domain____:$
 * $Namespace_:$
 * $Class_____:$
 * $Name______:$
 * $Variant___:$
 * $Revision__:$
 **********************************************************************************************************************
</BASDKey>*/
/*
 * Bsw_MemMap.h
 *
 *  Created on: Jul 31, 2017
 *      Author: NAI1HC
 */

/*
 **********************************************************************************************************************
 * Includes
 **********************************************************************************************************************
*/
#include "Mcu_Cfg_Machine.h"

/* <component>_MemMap.h for AUTOSAR Memory Mapping R4.0 Rev 3 */
/* MISRA RULE 19.15 VIOLATION: MemMap header concept - no protection against repeated inclusion intended */
/* ======================================================== */
#define MEMMAP_ERROR
/*Code sec*/
/*BSW_START_SEC_CODE*/
#if defined BSW_START_SEC_CODE
    #undef BSW_START_SEC_CODE
    #define CPU0_START_SEC_CODE
    #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CODE
    #undef BSW_STOP_SEC_CODE
    #define CPU0_STOP_SEC_CODE
    #undef MEMMAP_ERROR
/*BSW_START_SEC_DEFAULT_CODE*/
#elif defined BSW_START_SEC_DEFAULT_CODE
    #undef BSW_START_SEC_DEFAULT_CODE
    #define CPU0_START_SEC_CODE
    #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_CODE
    #undef BSW_STOP_SEC_DEFAULT_CODE
    #define CPU0_STOP_SEC_CODE
    #undef MEMMAP_ERROR
/* Code that shall go into fast code memory segments - Scratchpad Memory (SPRAM) */
#elif defined BSW_START_SEC_SPRAM_CODE
  #undef BSW_START_SEC_SPRAM_CODE
  //#define
  #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_SPRAM_CODE
  #undef BSW_STOP_SEC_SPRAM_CODE
  //#define
  #undef MEMMAP_ERROR

/* Start up measurement shall be supported:  Variables shall not be deleted/initialized during SW reset. */
#elif defined BSW_START_SEC_DEFAULT_RESET_SAFE_RAM0_32
  #undef BSW_START_SEC_DEFAULT_RESET_SAFE_RAM0_32
  //#define
  #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM0_32
  #undef BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM0_32
  //#define
  #undef MEMMAP_ERROR
#elif defined BSW_START_SEC_DEFAULT_RESET_SAFE_RAM0_UNSPECIFIED
  #undef BSW_START_SEC_DEFAULT_RESET_SAFE_RAM0_UNSPECIFIED
  //#define
  #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM0_UNSPECIFIED
  #undef BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM0_UNSPECIFIED
  //#define
  #undef MEMMAP_ERROR


/*Data sec uninitialized trusted*/
#elif defined BSW_START_SEC_VAR_CLEARED_8
    #undef BSW_START_SEC_VAR_CLEARED_8
    #define CPU0_START_SEC_RAM_CLEARED_8
    #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_CLEARED_8
    #undef BSW_STOP_SEC_VAR_CLEARED_8
    #define CPU0_STOP_SEC_RAM_CLEARED_8
    #undef MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_CLEARED_16
    #undef BSW_START_SEC_VAR_CLEARED_16
    #define CPU0_START_SEC_RAM_CLEARED_16
    #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_CLEARED_16
    #undef BSW_STOP_SEC_VAR_CLEARED_16
    #define CPU0_STOP_SEC_RAM_CLEARED_16
    #undef MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_CLEARED_32
    #undef BSW_START_SEC_VAR_CLEARED_32
    #define CPU0_START_SEC_RAM_CLEARED_32
    #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_CLEARED_32
    #undef BSW_STOP_SEC_VAR_CLEARED_32
    #define CPU0_STOP_SEC_RAM_CLEARED_32
    #undef MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_VAR_CLEARED_UNSPECIFIED
    #define CPU0_START_SEC_RAM_CLEARED_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_CLEARED_UNSPECIFIED
    #define CPU0_STOP_SEC_RAM_CLEARED_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_CLEARED_BOOL
    #undef BSW_START_SEC_VAR_CLEARED_BOOL
    #define CPU0_START_SEC_RAM_CLEARED_BOOL
    #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_CLEARED_BOOL
    #undef BSW_STOP_SEC_VAR_CLEARED_BOOL
    #define CPU0_STOP_SEC_RAM_CLEARED_BOOL
    #undef MEMMAP_ERROR
/* Used for global or static variables that are
    cleared to zero after every reset */
#elif defined BSW_START_SEC_DEFAULT_RAM0_CLEARED_8
    #undef BSW_START_SEC_DEFAULT_RAM0_CLEARED_8
    #define CPU0_START_SEC_RAM_CLEARED_8
    #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_8
    #undef BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_8
    #define CPU0_STOP_SEC_RAM_CLEARED_8
    #undef MEMMAP_ERROR
#elif defined BSW_START_SEC_DEFAULT_RAM0_CLEARED_16
    #undef BSW_START_SEC_DEFAULT_RAM0_CLEARED_16
    #define CPU0_START_SEC_RAM_CLEARED_16
    #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_16
    #undef BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_16
    #define CPU0_STOP_SEC_RAM_CLEARED_16
    #undef MEMMAP_ERROR
#elif defined BSW_START_SEC_DEFAULT_RAM0_CLEARED_32
    #undef BSW_START_SEC_DEFAULT_RAM0_CLEARED_32
    #define CPU0_START_SEC_RAM_CLEARED_32
    #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_32
    #undef BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_32
    #define CPU0_STOP_SEC_RAM_CLEARED_32
    #undef MEMMAP_ERROR
#elif defined BSW_START_SEC_DEFAULT_RAM0_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_RAM0_CLEARED_UNSPECIFIED
    #define CPU0_START_SEC_RAM_CLEARED_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_UNSPECIFIED
    #define CPU0_STOP_SEC_RAM_CLEARED_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined BSW_START_SEC_DEFAULT_RAM0_CLEARED_BOOL
    #undef BSW_START_SEC_DEFAULT_RAM0_CLEARED_BOOL
    #define CPU0_START_SEC_RAM_CLEARED_BOOL
    #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_BOOL
    #undef BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_BOOL
    #define CPU0_STOP_SEC_RAM_CLEARED_BOOL
    #undef MEMMAP_ERROR
/*Data sec initialized trusted*/
#elif defined BSW_START_SEC_VAR_INIT_8
    #undef BSW_START_SEC_VAR_INIT_8
    #define CPU0_START_SEC_RAM_INIT_8
    #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_INIT_8
    #undef BSW_STOP_SEC_VAR_INIT_8
    #define CPU0_STOP_SEC_RAM_INIT_8
    #undef MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_INIT_16
    #undef BSW_START_SEC_VAR_INIT_16
    #define CPU0_START_SEC_RAM_INIT_16
    #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_INIT_16
    #undef BSW_STOP_SEC_VAR_INIT_16
    #define CPU0_STOP_SEC_RAM_INIT_16
    #undef MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_INIT_32
    #undef BSW_START_SEC_VAR_INIT_32
    #define CPU0_START_SEC_RAM_INIT_32
    #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_INIT_32
    #undef BSW_STOP_SEC_VAR_INIT_32
    #define CPU0_STOP_SEC_RAM_INIT_32
    #undef MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_INIT_UNSPECIFIED
    #undef BSW_START_SEC_VAR_INIT_UNSPECIFIED
    #define CPU0_START_SEC_RAM_INIT_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_INIT_UNSPECIFIED
    #define CPU0_STOP_SEC_RAM_INIT_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_INIT_BOOL
    #undef BSW_START_SEC_VAR_INIT_BOOL
    #define CPU0_START_SEC_RAM_INIT_BOOL
    #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_INIT_BOOL
    #undef BSW_STOP_SEC_VAR_INIT_BOOL
    #define CPU0_STOP_SEC_RAM_INIT_BOOL
    #undef MEMMAP_ERROR
/*DEFAULT_RAM0*/
#elif defined BSW_START_SEC_DEFAULT_RAM0_INIT_8
    #undef BSW_START_SEC_DEFAULT_RAM0_INIT_8
    #define CPU0_START_SEC_RAM_INIT_8
    #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_INIT_8
    #undef BSW_STOP_SEC_DEFAULT_RAM0_INIT_8
    #define CPU0_STOP_SEC_RAM_INIT_8
    #undef MEMMAP_ERROR
#elif defined BSW_START_SEC_DEFAULT_RAM0_INIT_16
    #undef BSW_START_SEC_DEFAULT_RAM0_INIT_16
    #define CPU0_START_SEC_RAM_INIT_16
    #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_INIT_16
    #undef BSW_STOP_SEC_DEFAULT_RAM0_INIT_16
    #define CPU0_STOP_SEC_RAM_INIT_16
    #undef MEMMAP_ERROR
#elif defined BSW_START_SEC_DEFAULT_RAM0_INIT_32
    #undef BSW_START_SEC_DEFAULT_RAM0_INIT_32
    #define CPU0_START_SEC_RAM_INIT_32
    #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_INIT_32
    #undef BSW_STOP_SEC_DEFAULT_RAM0_INIT_32
    #define CPU0_STOP_SEC_RAM_INIT_32
    #undef MEMMAP_ERROR
#elif defined BSW_START_SEC_DEFAULT_RAM0_INIT_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_RAM0_INIT_UNSPECIFIED
    #define CPU0_START_SEC_RAM_INIT_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_RAM0_INIT_UNSPECIFIED
    #define CPU0_STOP_SEC_RAM_INIT_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined BSW_START_SEC_DEFAULT_RAM0_INIT_BOOL
    #undef BSW_START_SEC_DEFAULT_RAM0_INIT_BOOL
    #define CPU0_START_SEC_RAM_INIT_BOOL
    #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_INIT_BOOL
    #undef BSW_STOP_SEC_DEFAULT_RAM0_INIT_BOOL
    #define CPU0_STOP_SEC_RAM_INIT_BOOL
    #undef MEMMAP_ERROR
/*Data sec read only trusted*/
#elif defined BSW_START_SEC_CONST_8
    #undef BSW_START_SEC_CONST_8
    #define CPU0_START_SEC_CONST_8
    #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONST_8
    #undef BSW_STOP_SEC_CONST_8
    #define CPU0_STOP_SEC_CONST_8
    #undef MEMMAP_ERROR
#elif defined BSW_START_SEC_CONST_16
    #undef BSW_START_SEC_CONST_16
    #define CPU0_START_SEC_CONST_16
    #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONST_16
    #undef BSW_STOP_SEC_CONST_16
    #define CPU0_STOP_SEC_CONST_16
    #undef MEMMAP_ERROR
#elif defined BSW_START_SEC_CONST_32
    #undef BSW_START_SEC_CONST_32
    #define CPU0_START_SEC_CONST_32
    #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONST_32
    #undef BSW_STOP_SEC_CONST_32
    #define CPU0_STOP_SEC_CONST_32
    #undef MEMMAP_ERROR
#elif defined BSW_START_SEC_CONST_UNSPECIFIED
    #undef BSW_START_SEC_CONST_UNSPECIFIED
    #define CPU0_START_SEC_CONST_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONST_UNSPECIFIED
    #undef BSW_STOP_SEC_CONST_UNSPECIFIED
    #define CPU0_STOP_SEC_CONST_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined BSW_START_SEC_CONST_BOOL
    #undef BSW_START_SEC_CONST_BOOL
    #define CPU0_START_SEC_CONST_BOOL
    #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONST_BOOL
    #undef BSW_STOP_SEC_CONST_BOOL
    #define CPU0_STOP_SEC_CONST_BOOL
    #undef MEMMAP_ERROR
/*Data sec read only default trusted*/
#elif defined BSW_START_SEC_DEFAULT_CONST_8
    #undef BSW_START_SEC_DEFAULT_CONST_8
    #define CPU0_START_SEC_CONST_8
    #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_CONST_8
    #undef BSW_STOP_SEC_DEFAULT_CONST_8
    #define CPU0_STOP_SEC_CONST_8
    #undef MEMMAP_ERROR
#elif defined BSW_START_SEC_DEFAULT_CONST_16
    #undef BSW_START_SEC_DEFAULT_CONST_16
    #define CPU0_START_SEC_CONST_16
    #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_CONST_16
    #undef BSW_STOP_SEC_DEFAULT_CONST_16
    #define CPU0_STOP_SEC_CONST_16
    #undef MEMMAP_ERROR
#elif defined BSW_START_SEC_DEFAULT_CONST_32
    #undef BSW_START_SEC_DEFAULT_CONST_32
    #define CPU0_START_SEC_CONST_32
    #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_CONST_32
    #undef BSW_STOP_SEC_DEFAULT_CONST_32
    #define CPU0_STOP_SEC_CONST_32
    #undef MEMMAP_ERROR
#elif defined BSW_START_SEC_DEFAULT_CONST_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_CONST_UNSPECIFIED
    #define CPU0_START_SEC_CONST_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_CONST_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_CONST_UNSPECIFIED
    #define CPU0_STOP_SEC_CONST_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined BSW_START_SEC_DEFAULT_CONST_BOOL
    #undef BSW_START_SEC_DEFAULT_CONST_BOOL
    #define CPU0_START_SEC_CONST_BOOL
    #undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_CONST_BOOL
    #undef BSW_STOP_SEC_DEFAULT_CONST_BOOL
    #define CPU0_STOP_SEC_CONST_BOOL
    #undef MEMMAP_ERROR

/**************************************/
/******  SHARED TRUSTED CODE  *********/
/**************************************/
#elif defined BSW_SHARED_TRUSTED_START_SEC_CODE
    #define SHARED_TRUSTED_START_SEC_CODE
	#undef BSW_SHARED_TRUSTED_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_TRUSTED_STOP_SEC_CODE
    #define SHARED_TRUSTED_STOP_SEC_CODE
	#undef BSW_SHARED_TRUSTED_STOP_SEC_CODE
	#undef MEMMAP_ERROR

/*********************************/
/******  SHARED CODE  ************/
/*********************************/
/*(used by both trusted & un-trusted)*/
#elif defined BSW_SHARED_START_SEC_CODE
    #define SHARED_START_SEC_CODE
	#undef BSW_SHARED_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_STOP_SEC_CODE
    #define SHARED_STOP_SEC_CODE
	#undef BSW_SHARED_STOP_SEC_CODE
	#undef MEMMAP_ERROR

/**********************************/
/******  DEFAULT CODE  ************/
/**********************************/
#elif defined BSW_DEFAULT_START_SEC_CODE
    #define DEFAULT_START_SEC_CODE
	#undef BSW_DEFAULT_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif defined BSW_DEFAULT_STOP_SEC_CODE
    #define DEFAULT_STOP_SEC_CODE
	#undef BSW_DEFAULT_STOP_SEC_CODE
	#undef MEMMAP_ERROR

/**************************************/
/******  SHARED TRUSTED DATA  *********/
/**************************************/
/*Shared trusted data sec initialized*/
#elif defined BSW_SHARED_TRUSTED_START_SEC_RAM_INIT_UNSPECIFIED
    #define  SHARED_TRUSTED_START_SEC_RAM_INIT_UNSPECIFIED
    #undef BSW_SHARED_TRUSTED_START_SEC_RAM_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_TRUSTED_STOP_SEC_RAM_INIT_UNSPECIFIED
    #define SHARED_TRUSTED_STOP_SEC_RAM_INIT_UNSPECIFIED
	#undef BSW_SHARED_TRUSTED_STOP_SEC_RAM_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_TRUSTED_START_SEC_RAM_INIT_BOOL
    #define  SHARED_TRUSTED_START_SEC_RAM_INIT_BOOL
    #undef BSW_SHARED_TRUSTED_START_SEC_RAM_INIT_BOOL
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_TRUSTED_STOP_SEC_RAM_INIT_BOOL
    #define SHARED_TRUSTED_STOP_SEC_RAM_INIT_BOOL
	#undef BSW_SHARED_TRUSTED_STOP_SEC_RAM_INIT_BOOL
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_TRUSTED_START_SEC_RAM_INIT_8
    #define  SHARED_TRUSTED_START_SEC_RAM_INIT_8
    #undef BSW_SHARED_TRUSTED_START_SEC_RAM_INIT_8
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_TRUSTED_STOP_SEC_RAM_INIT_8
    #define SHARED_TRUSTED_STOP_SEC_RAM_INIT_8
	#undef BSW_SHARED_TRUSTED_STOP_SEC_RAM_INIT_8
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_TRUSTED_START_SEC_RAM_INIT_16
    #define  SHARED_TRUSTED_START_SEC_RAM_INIT_16
    #undef BSW_SHARED_TRUSTED_START_SEC_RAM_INIT_16
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_TRUSTED_STOP_SEC_RAM_INIT_16
    #define SHARED_TRUSTED_STOP_SEC_RAM_INIT_16
	#undef BSW_SHARED_TRUSTED_STOP_SEC_RAM_INIT_16
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_TRUSTED_START_SEC_RAM_INIT_32
    #define  SHARED_TRUSTED_START_SEC_RAM_INIT_32
    #undef BSW_SHARED_TRUSTED_START_SEC_RAM_INIT_32
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_TRUSTED_STOP_SEC_RAM_INIT_32
    #define SHARED_TRUSTED_STOP_SEC_RAM_INIT_32
	#undef BSW_SHARED_TRUSTED_STOP_SEC_RAM_INIT_32
	#undef MEMMAP_ERROR

/*Shared trusted data sec uninitialized*/
#elif defined BSW_SHARED_TRUSTED_START_SEC_RAM_CLEARED_UNSPECIFIED
    #define  SHARED_TRUSTED_START_SEC_RAM_CLEARED_UNSPECIFIED
    #undef BSW_SHARED_TRUSTED_START_SEC_RAM_CLEARED_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_TRUSTED_STOP_SEC_RAM_CLEARED_UNSPECIFIED
    #define SHARED_TRUSTED_STOP_SEC_RAM_CLEARED_UNSPECIFIED
	#undef BSW_SHARED_TRUSTED_STOP_SEC_RAM_CLEARED_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_TRUSTED_START_SEC_RAM_CLEARED_BOOL
    #define  SHARED_TRUSTED_START_SEC_RAM_CLEARED_BOOL
    #undef BSW_SHARED_TRUSTED_START_SEC_RAM_CLEARED_BOOL
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_TRUSTED_STOP_SEC_RAM_CLEARED_BOOL
    #define SHARED_TRUSTED_STOP_SEC_RAM_CLEARED_BOOL
	#undef BSW_SHARED_TRUSTED_STOP_SEC_RAM_CLEARED_BOOL
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_TRUSTED_START_SEC_RAM_CLEARED_8
    #define  SHARED_TRUSTED_START_SEC_RAM_CLEARED_8
    #undef BSW_SHARED_TRUSTED_START_SEC_RAM_CLEARED_8
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_TRUSTED_STOP_SEC_RAM_CLEARED_8
    #define SHARED_TRUSTED_STOP_SEC_RAM_CLEARED_8
	#undef BSW_SHARED_TRUSTED_STOP_SEC_RAM_CLEARED_8
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_TRUSTED_START_SEC_RAM_CLEARED_16
    #define  SHARED_TRUSTED_START_SEC_RAM_CLEARED_16
    #undef BSW_SHARED_TRUSTED_START_SEC_RAM_CLEARED_16
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_TRUSTED_STOP_SEC_RAM_CLEARED_16
    #define SHARED_TRUSTED_STOP_SEC_RAM_CLEARED_16
	#undef BSW_SHARED_TRUSTED_STOP_SEC_RAM_CLEARED_16
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_TRUSTED_START_SEC_RAM_CLEARED_32
    #define  SHARED_TRUSTED_START_SEC_RAM_CLEARED_32
    #undef BSW_SHARED_TRUSTED_START_SEC_RAM_CLEARED_32
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_TRUSTED_STOP_SEC_RAM_CLEARED_32
    #define SHARED_TRUSTED_STOP_SEC_RAM_CLEARED_32
	#undef BSW_SHARED_TRUSTED_STOP_SEC_RAM_CLEARED_32
	#undef MEMMAP_ERROR

/*Shared trusted readonly data sec*/
#elif defined BSW_SHARED_TRUSTED_START_SEC_CONST_UNSPECIFIED
    #define  SHARED_TRUSTED_START_SEC_CONST_UNSPECIFIED
    #undef BSW_SHARED_TRUSTED_START_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_TRUSTED_STOP_SEC_CONST_UNSPECIFIED
    #define SHARED_TRUSTED_STOP_SEC_CONST_UNSPECIFIED
	#undef BSW_SHARED_TRUSTED_STOP_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_TRUSTED_START_SEC_CONST_BOOL
    #define  SHARED_TRUSTED_START_SEC_CONST_BOOL
    #undef BSW_SHARED_TRUSTED_START_SEC_CONST_BOOL
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_TRUSTED_STOP_SEC_CONST_BOOL
    #define SHARED_TRUSTED_STOP_SEC_CONST_BOOL
	#undef BSW_SHARED_TRUSTED_STOP_SEC_CONST_BOOL
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_TRUSTED_START_SEC_CONST_8
    #define  SHARED_TRUSTED_START_SEC_CONST_8
    #undef BSW_SHARED_TRUSTED_START_SEC_CONST_8
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_TRUSTED_STOP_SEC_CONST_8
    #define SHARED_TRUSTED_STOP_SEC_CONST_8
	#undef BSW_SHARED_TRUSTED_STOP_SEC_CONST_8
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_TRUSTED_START_SEC_CONST_16
    #define  SHARED_TRUSTED_START_SEC_CONST_16
    #undef BSW_SHARED_TRUSTED_START_SEC_CONST_16
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_TRUSTED_STOP_SEC_CONST_16
    #define SHARED_TRUSTED_STOP_SEC_CONST_16
	#undef BSW_SHARED_TRUSTED_STOP_SEC_CONST_16
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_TRUSTED_START_SEC_CONST_32
    #define  SHARED_TRUSTED_START_SEC_CONST_32
    #undef BSW_SHARED_TRUSTED_START_SEC_CONST_32
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_TRUSTED_STOP_SEC_CONST_32
    #define SHARED_TRUSTED_STOP_SEC_CONST_32
	#undef BSW_SHARED_TRUSTED_STOP_SEC_CONST_32
	#undef MEMMAP_ERROR

/**************************************/
/******  SHARED DATA  *********/
/**************************************/
/*Shared data sec initialized*/
#elif defined BSW_SHARED_START_SEC_RAM_INIT_UNSPECIFIED
    #define  SHARED_START_SEC_RAM_INIT_UNSPECIFIED
    #undef BSW_SHARED_START_SEC_RAM_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_STOP_SEC_RAM_INIT_UNSPECIFIED
    #define SHARED_STOP_SEC_RAM_INIT_UNSPECIFIED
	#undef BSW_SHARED_STOP_SEC_RAM_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_START_SEC_RAM_INIT_BOOL
    #define  SHARED_START_SEC_RAM_INIT_BOOL
    #undef BSW_SHARED_START_SEC_RAM_INIT_BOOL
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_STOP_SEC_RAM_INIT_BOOL
    #define SHARED_STOP_SEC_RAM_INIT_BOOL
	#undef BSW_SHARED_STOP_SEC_RAM_INIT_BOOL
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_START_SEC_RAM_INIT_8
    #define  SHARED_START_SEC_RAM_INIT_8
    #undef BSW_SHARED_START_SEC_RAM_INIT_8
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_STOP_SEC_RAM_INIT_8
    #define SHARED_STOP_SEC_RAM_INIT_8
	#undef BSW_SHARED_STOP_SEC_RAM_INIT_8
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_START_SEC_RAM_INIT_16
    #define  SHARED_START_SEC_RAM_INIT_16
    #undef BSW_SHARED_START_SEC_RAM_INIT_16
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_STOP_SEC_RAM_INIT_16
    #define SHARED_STOP_SEC_RAM_INIT_16
	#undef BSW_SHARED_STOP_SEC_RAM_INIT_16
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_START_SEC_RAM_INIT_32
    #define  SHARED_START_SEC_RAM_INIT_32
    #undef BSW_SHARED_START_SEC_RAM_INIT_32
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_STOP_SEC_RAM_INIT_32
    #define SHARED_STOP_SEC_RAM_INIT_32
	#undef BSW_SHARED_STOP_SEC_RAM_INIT_32
	#undef MEMMAP_ERROR

/*Shared data sec uninitialized*/
#elif defined BSW_SHARED_START_SEC_RAM_CLEARED_UNSPECIFIED
    #define  SHARED_START_SEC_RAM_CLEARED_UNSPECIFIED
    #undef BSW_SHARED_START_SEC_RAM_CLEARED_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_STOP_SEC_RAM_CLEARED_UNSPECIFIED
    #define SHARED_STOP_SEC_RAM_CLEARED_UNSPECIFIED
	#undef BSW_SHARED_STOP_SEC_RAM_CLEARED_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_START_SEC_RAM_CLEARED_BOOL
    #define  SHARED_START_SEC_RAM_CLEARED_BOOL
    #undef BSW_SHARED_START_SEC_RAM_CLEARED_BOOL
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_STOP_SEC_RAM_CLEARED_BOOL
    #define SHARED_STOP_SEC_RAM_CLEARED_BOOL
	#undef BSW_SHARED_STOP_SEC_RAM_CLEARED_BOOL
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_START_SEC_RAM_CLEARED_8
    #define  SHARED_START_SEC_RAM_CLEARED_8
    #undef BSW_SHARED_START_SEC_RAM_CLEARED_8
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_STOP_SEC_RAM_CLEARED_8
    #define SHARED_STOP_SEC_RAM_CLEARED_8
	#undef BSW_SHARED_STOP_SEC_RAM_CLEARED_8
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_START_SEC_RAM_CLEARED_16
    #define  SHARED_START_SEC_RAM_CLEARED_16
    #undef BSW_SHARED_START_SEC_RAM_CLEARED_16
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_STOP_SEC_RAM_CLEARED_16
    #define SHARED_STOP_SEC_RAM_CLEARED_16
	#undef BSW_SHARED_STOP_SEC_RAM_CLEARED_16
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_START_SEC_RAM_CLEARED_32
    #define  SHARED_START_SEC_RAM_CLEARED_32
    #undef BSW_SHARED_START_SEC_RAM_CLEARED_32
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_STOP_SEC_RAM_CLEARED_32
    #define SHARED_STOP_SEC_RAM_CLEARED_32
	#undef BSW_SHARED_STOP_SEC_RAM_CLEARED_32
	#undef MEMMAP_ERROR

/*Shared data sec initialized; readonly for un-trusted*/
#elif defined BSW_SHARED_RO_START_SEC_RAM_INIT_UNSPECIFIED
    #define  SHARED_RO_START_SEC_RAM_INIT_UNSPECIFIED
    #undef BSW_SHARED_RO_START_SEC_RAM_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_RO_STOP_SEC_RAM_INIT_UNSPECIFIED
    #define SHARED_RO_STOP_SEC_RAM_INIT_UNSPECIFIED
	#undef BSW_SHARED_RO_STOP_SEC_RAM_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_RO_START_SEC_RAM_INIT_BOOL
    #define  SHARED_RO_START_SEC_RAM_INIT_BOOL
    #undef BSW_SHARED_RO_START_SEC_RAM_INIT_BOOL
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_RO_STOP_SEC_RAM_INIT_BOOL
    #define SHARED_RO_STOP_SEC_RAM_INIT_BOOL
	#undef BSW_SHARED_RO_STOP_SEC_RAM_INIT_BOOL
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_RO_START_SEC_RAM_INIT_8
    #define  SHARED_RO_START_SEC_RAM_INIT_8
    #undef BSW_SHARED_RO_START_SEC_RAM_INIT_8
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_RO_STOP_SEC_RAM_INIT_8
    #define SHARED_RO_STOP_SEC_RAM_INIT_8
	#undef BSW_SHARED_RO_STOP_SEC_RAM_INIT_8
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_RO_START_SEC_RAM_INIT_16
    #define  SHARED_RO_START_SEC_RAM_INIT_16
    #undef BSW_SHARED_RO_START_SEC_RAM_INIT_16
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_RO_STOP_SEC_RAM_INIT_16
    #define SHARED_RO_STOP_SEC_RAM_INIT_16
	#undef BSW_SHARED_RO_STOP_SEC_RAM_INIT_16
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_RO_START_SEC_RAM_INIT_32
    #define  SHARED_RO_START_SEC_RAM_INIT_32
    #undef BSW_SHARED_RO_START_SEC_RAM_INIT_32
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_RO_STOP_SEC_RAM_INIT_32
    #define SHARED_RO_STOP_SEC_RAM_INIT_32
	#undef BSW_SHARED_RO_STOP_SEC_RAM_INIT_32
	#undef MEMMAP_ERROR

/*Shared data sec uninitialized; readonly for un-trusted*/
#elif defined BSW_SHARED_RO_START_SEC_RAM_CLEARED_UNSPECIFIED
    #define  SHARED_RO_START_SEC_RAM_CLEARED_UNSPECIFIED
    #undef BSW_SHARED_RO_START_SEC_RAM_CLEARED_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_RO_STOP_SEC_RAM_CLEARED_UNSPECIFIED
    #define SHARED_RO_STOP_SEC_RAM_CLEARED_UNSPECIFIED
	#undef BSW_SHARED_RO_STOP_SEC_RAM_CLEARED_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_RO_START_SEC_RAM_CLEARED_BOOL
    #define  SHARED_RO_START_SEC_RAM_CLEARED_BOOL
    #undef BSW_SHARED_RO_START_SEC_RAM_CLEARED_BOOL
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_RO_STOP_SEC_RAM_CLEARED_BOOL
    #define SHARED_RO_STOP_SEC_RAM_CLEARED_BOOL
	#undef BSW_SHARED_RO_STOP_SEC_RAM_CLEARED_BOOL
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_RO_START_SEC_RAM_CLEARED_8
    #define  SHARED_RO_START_SEC_RAM_CLEARED_8
    #undef BSW_SHARED_RO_START_SEC_RAM_CLEARED_8
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_RO_STOP_SEC_RAM_CLEARED_8
    #define SHARED_RO_STOP_SEC_RAM_CLEARED_8
	#undef BSW_SHARED_RO_STOP_SEC_RAM_CLEARED_8
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_RO_START_SEC_RAM_CLEARED_16
    #define  SHARED_RO_START_SEC_RAM_CLEARED_16
    #undef BSW_SHARED_RO_START_SEC_RAM_CLEARED_16
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_RO_STOP_SEC_RAM_CLEARED_16
    #define SHARED_RO_STOP_SEC_RAM_CLEARED_16
	#undef BSW_SHARED_RO_STOP_SEC_RAM_CLEARED_16
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_RO_START_SEC_RAM_CLEARED_32
    #define  SHARED_RO_START_SEC_RAM_CLEARED_32
    #undef BSW_SHARED_RO_START_SEC_RAM_CLEARED_32
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_RO_STOP_SEC_RAM_CLEARED_32
    #define SHARED_RO_STOP_SEC_RAM_CLEARED_32
	#undef BSW_SHARED_RO_STOP_SEC_RAM_CLEARED_32
	#undef MEMMAP_ERROR

/*Shared readonly data sec*/
#elif defined BSW_SHARED_START_SEC_CONST_UNSPECIFIED
    #define  SHARED_START_SEC_CONST_UNSPECIFIED
    #undef BSW_SHARED_START_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_STOP_SEC_CONST_UNSPECIFIED
    #define SHARED_STOP_SEC_CONST_UNSPECIFIED
	#undef BSW_SHARED_STOP_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_START_SEC_CONST_BOOL
    #define  SHARED_START_SEC_CONST_BOOL
    #undef BSW_SHARED_START_SEC_CONST_BOOL
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_STOP_SEC_CONST_BOOL
    #define SHARED_STOP_SEC_CONST_BOOL
	#undef BSW_SHARED_STOP_SEC_CONST_BOOL
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_START_SEC_CONST_8
    #define  SHARED_START_SEC_CONST_8
    #undef BSW_SHARED_START_SEC_CONST_8
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_STOP_SEC_CONST_8
    #define SHARED_STOP_SEC_CONST_8
	#undef BSW_SHARED_STOP_SEC_CONST_8
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_START_SEC_CONST_16
    #define  SHARED_START_SEC_CONST_16
    #undef BSW_SHARED_START_SEC_CONST_16
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_STOP_SEC_CONST_16
    #define SHARED_STOP_SEC_CONST_16
	#undef BSW_SHARED_STOP_SEC_CONST_16
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_START_SEC_CONST_32
    #define  SHARED_START_SEC_CONST_32
    #undef BSW_SHARED_START_SEC_CONST_32
	#undef MEMMAP_ERROR
#elif defined BSW_SHARED_STOP_SEC_CONST_32
    #define SHARED_STOP_SEC_CONST_32
	#undef BSW_SHARED_STOP_SEC_CONST_32
	#undef MEMMAP_ERROR




/// add by allen
#elif defined BSW_START_SEC_CONFIG_DATA_UNSPECIFIED
    #undef  BSW_START_SEC_CONFIG_DATA_UNSPECIFIED
    #define CPU0_START_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONFIG_DATA_UNSPECIFIED
    #undef BSW_STOP_SEC_CONFIG_DATA_UNSPECIFIED
    #define CPU0_STOP_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR

/*
#elif defined BSW_START_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED
    #undef  BSW_START_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED
    #undef BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED
	#undef MEMMAP_ERROR
*/


#elif defined BSW_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED
 //   #define CPU0_START_SEC_RAM_CLEARED_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SAVED_ZONE_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_SAVED_ZONE_UNSPECIFIED
 //   #define CPU0_STOP_SEC_RAM_CLEARED_UNSPECIFIED
	#undef MEMMAP_ERROR
////
#endif

#ifdef MEMMAP_ERROR
//#error "Bsw_MemMap.h, wrong #pragma command"  allen
#undef MEMMAP_ERROR
#else

#include "MemMap.h"
#endif
