
/*
 * File generated by TESSY.
 * DO NOT EDIT THIS FILE!
 */

/* Source: is_val_in_range.c */

/* Allow main as testobject */
#define main  ts_main
#define TESSY_SOURCE_01

/* stubfunction counters */
#include "ts_stubcounter.h"

// This is a very basic program to demonstrate the integration 
// of Tessy and HiTOP, the debugger from Hitex.
// (c) Hitex Systementwicklung GmbH 2001, www.hitex.de
//
// $Revision: 1$

struct range {int range_start; int range_len;};

typedef int value;

typedef enum {no, yes} result;

// Checks if r1.start <= v1 < (r1.start + r1.len),
// e.g. r1.start = 5, r1.len = 2
// ==> v1 == 4 ---> no
//     v1 == 5 ---> yes
//     v1 == 6 ---> yes
//     v1 == 7 ---> no
// However, the implementation is intentionally
// erroneous: v1 == 7 results "yes" instead of "no"!
//

result is_value_in_range (struct range r1, value v1)
{
	if (v1 < r1.range_start)
		return no;

	if (v1 > (r1.range_start + r1.range_len))
		return no;

	return yes;

}


/****************************************************************/
/* T E S S Y  C O D E                                           */
/****************************************************************/

#define __TS_THIS_IS_THE_SLAVE__

/*
 * external variables
 */

#include "tstcomm.h"
#include "ts_is_value_in_range_s.h"
#include "ts_usr.h"
#include "ts_stub_declarations.h"


/*
 * Parameter
 */
struct range TESSY_TESTOBJECT_PARM_01;
int TESSY_TESTOBJECT_PARM_02;

/*
 * Returnvalue
 */
result TS_TESTOBJECT_RETURN;

/*
 * Stub Variables
 */
extern char TESSY_use_value(void);

/*
 * Functions to read/write Testdata for structs/unions
 */
void TESSY_receive_rangedefaultdefault(struct range * ts_struct_pointer);

void TESSY_receive_rangedefaultdefault(struct range * ts_struct_pointer) {
   if (TESSY_use_value()) {ts_struct_pointer->range_start = tstcomm_get_long();}

   if (TESSY_use_value()) {ts_struct_pointer->range_len = tstcomm_get_long();}

}


/*
 * Receive Testdata from master
 */

   /* Parameter */
void TESSY_receive_parameter(void) {
   TESSY_receive_rangedefaultdefault((struct range  * )&TESSY_TESTOBJECT_PARM_01);
   if (TESSY_use_value()) {TESSY_TESTOBJECT_PARM_02 = tstcomm_get_long();}
}

void TESSY_receive_TD01(void) {
}


   /* Parameter */
void TESSY_send_parameter(void) {
}

void TESSY_send_TD01(void) {
}


/* Return */
void TESSY_send_return(void) {
   tstcomm_put_long((long)TS_TESTOBJECT_RETURN);
}

/*
 * DO NOT EDIT THIS FILE!
 *
 * This file is automatically generated each time a test
 * is executed and all changes made to this file will be lost.
 */
#include "ts_usr.h"
#include "ts_is_value_in_range_s.h"


#include "tsteval.h"

#ifndef TS_CURRENT_TESTCASE_DEFINED
	/* Current Testcase / Teststep and repeatcount*/
	extern TESSY_uint32   TS_CURRENT_TESTCASE;
	extern TESSY_uint32   TS_CURRENT_TESTSTEP;
	extern TESSY_uint32   TS_REPEAT_COUNT;
#endif

#define r1 TESSY_TESTOBJECT_PARM_01
#define v1 TESSY_TESTOBJECT_PARM_02

/*
 * User definitions
 */


/*
* User code to execute before test execution starts.
 */
void ts_tobj_prolog (void) {

}

/*
* User code to execute after test execution finished.
 */
void ts_tobj_epilog (void) {

}

/*
 * This function is called each time just before
 * a specific testcase and teststep is executed.
 */
void ts_tc_prolog (void) {
}


/*
 * This function is called each time just after
 * a specific testcase and teststep was executed.
 */
void ts_tc_epilog (void) {
}

/* Undefine parameter defines */
#undef r1
#undef v1

void TESSY_TestobjectCall(void) {
   TS_TESTOBJECT_RETURN = is_value_in_range(TESSY_TESTOBJECT_PARM_01, TESSY_TESTOBJECT_PARM_02);
}

