/*
***********************************************************************************************************************
* 
* Product Info
* Isolar version: ISOLAR-AB 4.0.2
* Product release version: RTA-BSW 3.1.0
* 
***********************************************************************************************************************
*/

/********************************************************************************************************************/
/*                                                                                                                  */
/* TOOL-GENERATED SOURCECODE, DO NOT CHANGE                                                                         */
/*                                                                                                                  */
/********************************************************************************************************************/

#ifndef DEM_CFG_DEB_H
#define DEM_CFG_DEB_H

#include "Std_Types.h"

/* ---------------------------------------- */
/* DEM_CFG_DEBMONINTBASE                    */
/* ---------------------------------------- */
#define DEM_CFG_DEBMONINTERNAL_OFF  STD_OFF
#define DEM_CFG_DEBMONINTERNAL_ON   STD_ON
#define DEM_CFG_DEBMONINTERNAL  DEM_CFG_DEBMONINTERNAL_OFF

/* ---------------------------------------- */
/* DEM_CFG_DEBARTIMEBASE                    */
/* ---------------------------------------- */
#define DEM_CFG_DEBARTIMEBASE_OFF  STD_OFF
#define DEM_CFG_DEBARTIMEBASE_ON   STD_ON
#define DEM_CFG_DEBARTIMEBASE  DEM_CFG_DEBARTIMEBASE_OFF

/* ---------------------------------------- */
/* DEM_CFG_DEBCOUNTERBASEDCLASS             */
/* ---------------------------------------- */
#define DEM_CFG_DEBCOUNTERBASECLASS_OFF  STD_OFF
#define DEM_CFG_DEBCOUNTERBASECLASS_ON   STD_ON
#define DEM_CFG_DEBCOUNTERBASECLASS  DEM_CFG_DEBCOUNTERBASECLASS_ON

#define DEM_CFG_LIMIT_RELEVANTFOR_JUMPING_OFF  STD_OFF
#define DEM_CFG_LIMIT_RELEVANTFOR_JUMPING_ON   STD_ON
#define DEM_CFG_LIMIT_RELEVANTFOR_JUMPING DEM_CFG_LIMIT_RELEVANTFOR_JUMPING_OFF

#define DEM_CFG_DEFAULT_DEBCOUNTERCLASS_MAXLIMIT 32767
#define DEM_CFG_DEFAULT_DEBCOUNTERCLASS_MINLIMIT -32768
#define DEM_CFG_DEFAULT_DEBCOUNTERCLASS_JUMPUP_ENABLED TRUE
#define DEM_CFG_DEFAULT_DEBCOUNTERCLASS_JUMPUP_VALUE 0
#define DEM_CFG_DEFAULT_DEBCOUNTERCLASS_JUMPDOWN_ENABLED TRUE
#define DEM_CFG_DEFAULT_DEBCOUNTERCLASS_JUMPDOWN_VALUE 0

#define DEM_CFG_DEBCOUNTERBASECLASS_MINTHRESHOLD_OFF  STD_OFF
#define DEM_CFG_DEBCOUNTERBASECLASS_MINTHRESHOLD_ON   STD_ON
#define DEM_CFG_DEBCOUNTERBASECLASS_MINTHRESHOLD  DEM_CFG_DEBCOUNTERBASECLASS_MINTHRESHOLD_ON

#define DEM_CFG_DEBCOUNTERBASECLASS_MAXTHRESHOLD_OFF  STD_OFF
#define DEM_CFG_DEBCOUNTERBASECLASS_MAXTHRESHOLD_ON   STD_ON
#define DEM_CFG_DEBCOUNTERBASECLASS_MAXTHRESHOLD  DEM_CFG_DEBCOUNTERBASECLASS_MAXTHRESHOLD_ON

#define DEM_CFG_DEBCOUNTERBASECLASS_JUMPUPVALUE_OFF  STD_OFF
#define DEM_CFG_DEBCOUNTERBASECLASS_JUMPUPVALUE_ON   STD_ON
#define DEM_CFG_DEBCOUNTERBASECLASS_JUMPUPVALUE  DEM_CFG_DEBCOUNTERBASECLASS_JUMPUPVALUE_ON

#define DEM_CFG_DEBCOUNTERBASECLASS_JUMPDOWNVALUE_OFF  STD_OFF
#define DEM_CFG_DEBCOUNTERBASECLASS_JUMPDOWNVALUE_ON   STD_ON
#define DEM_CFG_DEBCOUNTERBASECLASS_JUMPDOWNVALUE  DEM_CFG_DEBCOUNTERBASECLASS_JUMPDOWNVALUE_ON

#define DEM_CFG_DEBCOUNTERBASECLASS_ISJUMPDOWN_OFF  STD_OFF
#define DEM_CFG_DEBCOUNTERBASECLASS_ISJUMPDOWN_ON   STD_ON
#define DEM_CFG_DEBCOUNTERBASECLASS_ISJUMPDOWN  DEM_CFG_DEBCOUNTERBASECLASS_ISJUMPDOWN_ON

#define DEM_CFG_DEBCOUNTERBASECLASS_ISJUMPUP_OFF  STD_OFF
#define DEM_CFG_DEBCOUNTERBASECLASS_ISJUMPUP_ON   STD_ON
#define DEM_CFG_DEBCOUNTERBASECLASS_ISJUMPUP  DEM_CFG_DEBCOUNTERBASECLASS_ISJUMPUP_ON

#define DEMRB_DEBOUNCECOUNTERSETS_SIZE                                 2
/** Offset of the CounterSet Id where the custom counter sets start */
#define DEMRB_DEBOUNCECOUNTERSETS_CUSTOMSETSOFFSET                     2

#define DemConf_DemRbDebounceCounterSet_Standard                       0
#define DemConf_DemRbDebounceCounterSet_Alternative                    1

#define DEM_CFG_DEBCOUNTERBASECLASS_PARAMSET_LENGTH 5

/*                 				ISJDOWN             ISJUP               MINLIMIT                      MAXLIMIT                      JDOWNValue          JUPValue            FDC_THRESHOLD       SUSPICIOUS_THRESHOLD STEPUP             STEPDOWN             */

#define DEM_CFG_DEBCOUNTERCLASS_PARAMSETS \
{ \
  { /* Default Debouncing Parameters */ \
   DEM_DEBCOUNTERBASECLASS_INIT (TRUE,               TRUE,               -20,                          20,                           0,                  0,                  DEM_CFG_DEFAULT_DEBCOUNTERCLASS_MAXLIMIT,DEM_MAXSINT16,1,   -1                  ), \
   DEM_DEBCOUNTERBASECLASS_INIT (TRUE,               TRUE,               -20,                          20,                           0,                  0,                  DEM_CFG_DEFAULT_DEBCOUNTERCLASS_MAXLIMIT,DEM_MAXSINT16,1,   -1                  ), \
   DEM_DEBCOUNTERBASECLASS_INIT (TRUE,               TRUE,               -1,                           1,                            0,                  0,                  DEM_CFG_DEFAULT_DEBCOUNTERCLASS_MAXLIMIT,DEM_MAXSINT16,1,   -1                  ), \
   DEM_DEBCOUNTERBASECLASS_INIT (TRUE,               TRUE,               -3,                           3,                            0,                  0,                  DEM_CFG_DEFAULT_DEBCOUNTERCLASS_MAXLIMIT,DEM_MAXSINT16,1,   -1                  ), \
   DEM_DEBCOUNTERBASECLASS_INIT (TRUE,               TRUE,               -10,                          10,                           0,                  0,                  DEM_CFG_DEFAULT_DEBCOUNTERCLASS_MAXLIMIT,DEM_MAXSINT16,1,   -1                  ), \
}, \
  { /* Alternative Debouncing Parameters */  \
   DEM_DEBCOUNTERBASECLASS_INIT (TRUE,               TRUE,               -20,                          20,                           0,                  0,                  DEM_CFG_DEFAULT_DEBCOUNTERCLASS_MAXLIMIT,DEM_MAXSINT16,1,   -1                  ), \
   DEM_DEBCOUNTERBASECLASS_INIT (TRUE,               TRUE,               -20,                          20,                           0,                  0,                  DEM_CFG_DEFAULT_DEBCOUNTERCLASS_MAXLIMIT,DEM_MAXSINT16,1,   -1                  ), \
   DEM_DEBCOUNTERBASECLASS_INIT (TRUE,               TRUE,               -1,                           1,                            0,                  0,                  DEM_CFG_DEFAULT_DEBCOUNTERCLASS_MAXLIMIT,DEM_MAXSINT16,1,   -1                  ), \
   DEM_DEBCOUNTERBASECLASS_INIT (TRUE,               TRUE,               -3,                           3,                            0,                  0,                  DEM_CFG_DEFAULT_DEBCOUNTERCLASS_MAXLIMIT,DEM_MAXSINT16,1,   -1                  ), \
   DEM_DEBCOUNTERBASECLASS_INIT (TRUE,               TRUE,               -10,                          10,                           0,                  0,                  DEM_CFG_DEFAULT_DEBCOUNTERCLASS_MAXLIMIT,DEM_MAXSINT16,1,   -1                  ), \
  }, \
}

#define DEM_DEBPARAMCLASS_IDX_CANSM_E_DEMDEBOUNCECOUNTERBASEDCLASS_NETWORK_0  0
#define DEM_DEBPARAMCLASS_IDX_CANSM_E_DEMDEBOUNCECOUNTERBASEDCLASS_NETWORK_1  1
#define DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_11001  2
#define DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003  3
#define DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_A100A  4

#define DEM_DEBPARAM_IDX_ADC_UPHASEBISTFAIL             DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_ADC_VPHASEBISTFAIL             DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_ADC_WPHASEBISTFAIL             DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_CANSM_E_BUS_OFF_NETWORK_0      DEM_DEBPARAMCLASS_IDX_CANSM_E_DEMDEBOUNCECOUNTERBASEDCLASS_NETWORK_0
#define DEM_DEBPARAM_IDX_CANSM_E_BUS_OFF_NETWORK_1      DEM_DEBPARAMCLASS_IDX_CANSM_E_DEMDEBOUNCECOUNTERBASEDCLASS_NETWORK_1
#define DEM_DEBPARAM_IDX_CAN_TIMEOUT                    DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_A100A
#define DEM_DEBPARAM_IDX_CPLD_ALIVECHKERR               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_CPLD_DI_EXDCLK_INFAIL          DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_CPLD_EXDCLKINFAIL              DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_CPLD_IPHAOC                    DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_CPLD_NEN_INFAIL                DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_CPLD_PARITYCHKERR              DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_CPLD_RX_SELFTEST_FAIL          DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_CPLD_SPICOMFAIL                DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_CPLD_SZTKT_INFAIL              DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_CPLD_SHORT_CIRCUIT_HS_INFAIL   DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_CPLD_SHORT_CIRCUIT_LS_INFAIL   DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_CPLD_UDCOVERVOLFAIL            DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_CPLD_UNDERVOL_HS_INFAIL        DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_CPLD_UNDERVOL_LS_INFAIL        DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_EPARK_OVERCURFAIL              DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_EPARK_POSMONSAMPFAIL           DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_EPARK_POSSAMPFAIL              DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_EPARK_SAMPFAIL                 DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_EVENT_NVM_READERR              DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_EVENT_NVM_WRITEERR             DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_FR_STORAGEERR                  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_HSPF_INVOPENERR                DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_HSPF_MOTOROPENERR              DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_HSPF_VERMATCHFAILUREERR        DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_HSPF_STIPHAOFFCALFAIL          DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_HSPF_TDBCTEMPCMPERR            DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_HVMCU_COMERR                   DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_HVMCU_DISCHRGDUTYERR           DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_HVMCU_DISCHRGFAIL              DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_HVMCU_DISCHRGFREQERR           DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_HVMCU_EMERPOWERSAPERR          DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_HVMCU_UARTCHECKFAILERR         DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_HVMCU_UARTLOSTFRAMEERR         DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_HVMCU_UDCCHECKERR              DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_HVMCU_UDCOVERFLAGLIMIT         DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_HVMCU_UDCOVERVOLERR            DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_IOHWAB_12VNARRSAMPERR          DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_IOHWAB_12VSAMPERR              DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_IOHWAB_12VWIDESAMPERR          DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_IOHWAB_18VLWBRGSAMPFAIL        DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_IOHWAB_18VUPBRGSAMPFAIL        DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_IOHWAB_1V3MCU_SAMPFAIL         DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_IOHWAB_3V3MCU_SAMPFAIL         DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_IOHWAB_5VQCOSAMPFAIL           DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_IOHWAB_5VQT1SAMPFAIL           DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_IOHWAB_5VQT2SAMPFAIL           DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_IOHWAB_CPLD1V8SAMPFAIL         DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_IOHWAB_CPLD3V3SAMPFAIL         DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_IOHWAB_CRASHFAIL               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_IOHWAB_DCLNKOVERVOLFAIL        DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_IOHWAB_IPHAOCFAIL              DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_IOHWAB_KL30OVERVOLERR          DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_IOHWAB_KL30SEVOVERVOLFAIL      DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_IOHWAB_KL30SEVUNDERVOLFAIL     DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_IOHWAB_KL30UNDERVOLERR         DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_IOHWAB_NEN33FAIL               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_IOHWAB_STTRSENORSHRFAIL        DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_IOHWAB_STTRTEMP1SAMPFAIL       DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_IOHWAB_STTRTEMP2SAMPFAIL       DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_IOHWAB_TCOOLANTSAMPFAIL        DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_IOHWAB_VDD5_D_SAMPFAIL         DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_IGBTDRV_COMERR                 DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_IGBTDRV_LWBRGFAULTAFAIL        DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_IGBTDRV_LWBRGFAULTBFAIL        DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_IGBTDRV_UPBRGFAULTAFAIL        DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_IGBTDRV_UPBRGFAULTBFAIL        DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_MDF_ALOFSNOPLAUSERR            DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_MDF_DIASHCIRNOPSBLERR          DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_MDF_EMACBLKDERR                DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_MDF_EMACBLKDWARN               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_MDF_ICTLRATERR                 DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_MDF_ISOVHIERR                  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_MDF_OPENCIRNOPSBLERR           DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_MDF_OPEROUTDRNGERR             DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_MDF_PHASELOSSFAULTERR          DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_MDF_PRFELDRVERR                DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_PCF_ACTOVTIERR                 DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_PCF_IDCOVERR                   DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_11001
#define DEM_DEBPARAM_IDX_PCF_SELFCHECKERR               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_PCF_SENCLBERR                  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_PCF_SENOVERR                   DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_PCF_STALLRETRYERR              DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_11001
#define DEM_DEBPARAM_IDX_PCF_STALLWARN                  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_PCF_UNEXPPOSERR                DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_RCF_ACCOVTIERR                 DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_RCF_ESTOFSERR                  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_RCF_FWLBWDOVTIERR              DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_RCF_FWLFWDOVTIERR              DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_RCF_OFSCLBFAIL                 DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_RCF_PSIOVERR                   DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_RSL_DOSERR                     DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_RSL_EXCERR                     DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_RSL_LOSERR                     DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_RSL_LOTERR                     DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_SCF_DISCHGOVTIFAIL             DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_SCF_LOWPWRSHTDWNOVTIFAIL       DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_SCF_RUNTODISCHARERR            DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_TPC_SPDOVHILIMFAIL             DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_TPC_SPDOVHIWARN                DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_TPC_TCOOLANTOVHIWARN           DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_TPC_TDBCOVHIWARN               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_TPC_TDBCOVLOWARN               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_TPC_TDBCUHILIMFAIL             DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_TPC_TDBCULOLIMFAIL             DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_TPC_TDBCVHILIMFAIL             DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_TPC_TDBCVLOLIMFAIL             DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_TPC_TDBCWHILIMFAIL             DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_TPC_TDBCWLOLIMFAIL             DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_TPC_TDRVBOARDOVHIWARN          DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_TPC_TIGBTOVHILIMERR            DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_TPC_TIGBTOVHIWARN              DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_TPC_TIGBTOVLOWARN              DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_TPC_TSTTROVHILIMFAIL           DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_TPC_TSTTROVHIWARN              DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_TPC_TSTTROVLOWARN              DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_TPC_IDCLNKOVCLIMFAIL           DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_TPC_IDCLNKOVCWARN              DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_TPC_UDCLNKOVVLIMFAIL           DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_TPC_UDCLNKOVWARN               DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_TPC_UDCLNKUNVLIMFAIL           DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003
#define DEM_DEBPARAM_IDX_TPC_UDCLNKUNVWARN              DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_31003

#define DEM_CFG_DEB_DEFINE_ALL_PARAMSETS \
static const Dem_DebCounterBaseClass_ParamSet  Dem_Cfg_DebCounterBaseClass_Paramsets[DEMRB_DEBOUNCECOUNTERSETS_SIZE][DEM_CFG_DEBCOUNTERBASECLASS_PARAMSET_LENGTH] = DEM_CFG_DEBCOUNTERCLASS_PARAMSETS; \


#define  DEM_CFG_DEB_CLASSES \
{ \
   { \
      NULL_PTR, \
      NULL_PTR, \
      NULL_PTR, \
      0, \
      NULL_PTR \
   } \
   ,{ \
      &Dem_DebCounterBaseClass_GetLimits, \
      NULL_PTR, \
      &Dem_Cfg_DebCounterBaseClass_Paramsets[DemConf_DemRbDebounceCounterSet_Standard], \
      DEM_CFG_DEBCOUNTERBASECLASS_PARAMSET_LENGTH, \
      &Dem_DebCounterBaseClass_Filter \
   } \
}

#define  DEM_CFG_DEB_NUMBEROFCLASSES  2

#define DEM_DEBMETH_IDX_ARCTRBASECLASS      (1)

/* Support Debouncer Reset After StorageCondition */
#define DEM_CFG_SUPPORT_DEB_RESET_AFTER_STOCO_OFF                                    0u
#define DEM_CFG_SUPPORT_DEB_RESET_AFTER_STOCO_ACCORDING_DEBOUNCEBEHAVIOR             1u

#define DEM_CFG_SUPPORT_DEB_RESET_AFTER_STOCO           DEM_CFG_SUPPORT_DEB_RESET_AFTER_STOCO_OFF

#endif

