/*
***********************************************************************************************************************
* 
* Product Info
* Isolar version: ISOLAR-AB 4.0.2
* Product release version: RTA-BSW 3.1.0
* 
***********************************************************************************************************************
*/

/********************************************************************************************************************/
/*                                                                                                                  */
/* TOOL-GENERATED SOURCECODE, DO NOT CHANGE                                                                         */
/*                                                                                                                  */
/********************************************************************************************************************/

#ifndef FIM_CFG_FIDS_H
#define FIM_CFG_FIDS_H

#include "FiM_Types.h"

/*  short name                          FId value */
#define FiMConf_FiMFID_FIM_ADC_UPhaseBISTFail    (1)
#define FiMConf_FiMFID_FIM_ADC_VPhaseBISTFail    (2)
#define FiMConf_FiMFID_FIM_ADC_WPhaseBISTFail    (3)
#define FiMConf_FiMFID_FIM_CANSM_E_BUS_OFF_NETWORK_0    (4)
#define FiMConf_FiMFID_FIM_Can_Timeout    (5)
#define FiMConf_FiMFID_FIM_CpldErr    (6)
#define FiMConf_FiMFID_FIM_Cpld_AliveChkErr    (7)
#define FiMConf_FiMFID_FIM_Cpld_DI_ExdClk_InFail    (8)
#define FiMConf_FiMFID_FIM_Cpld_ExdClkInFail    (9)
#define FiMConf_FiMFID_FIM_Cpld_IphaOC    (10)
#define FiMConf_FiMFID_FIM_Cpld_NEN_InFail    (11)
#define FiMConf_FiMFID_FIM_Cpld_ParityChkErr    (12)
#define FiMConf_FiMFID_FIM_Cpld_SPIComFail    (13)
#define FiMConf_FiMFID_FIM_Cpld_SZTKT_InFail    (14)
#define FiMConf_FiMFID_FIM_Cpld_Short_Circuit_HS_InFail    (15)
#define FiMConf_FiMFID_FIM_Cpld_Short_Circuit_LS_InFail    (16)
#define FiMConf_FiMFID_FIM_Cpld_UdcOverVolFail    (17)
#define FiMConf_FiMFID_FIM_Cpld_UnderVol_HS_InFail    (18)
#define FiMConf_FiMFID_FIM_Cpld_UnderVol_LS_InFail    (19)
#define FiMConf_FiMFID_FIM_Epark_OverCurFail    (20)
#define FiMConf_FiMFID_FIM_Epark_PosMonSampFail    (21)
#define FiMConf_FiMFID_FIM_Epark_PosSampFail    (22)
#define FiMConf_FiMFID_FIM_Epark_SampFail    (23)
#define FiMConf_FiMFID_FIM_Event_NvM_ReadErr    (24)
#define FiMConf_FiMFID_FIM_Event_NvM_WriteErr    (25)
#define FiMConf_FiMFID_FIM_FRStoErr    (26)
#define FiMConf_FiMFID_FIM_FR_StorageErr    (27)
#define FiMConf_FiMFID_FIM_HSPF_InvOpenErr    (28)
#define FiMConf_FiMFID_FIM_HSPF_MotorOpenErr    (29)
#define FiMConf_FiMFID_FIM_HSPF_VerMatchFailureErr    (30)
#define FiMConf_FiMFID_FIM_HSPF_stIphaOffCalFail    (31)
#define FiMConf_FiMFID_FIM_HSPF_tDBCTempCmpErr    (32)
#define FiMConf_FiMFID_FIM_HvMcu_ComErr    (33)
#define FiMConf_FiMFID_FIM_HvMcu_DisChrgDutyErr    (34)
#define FiMConf_FiMFID_FIM_HvMcu_DisChrgFail    (35)
#define FiMConf_FiMFID_FIM_HvMcu_DisChrgFreqErr    (36)
#define FiMConf_FiMFID_FIM_HvMcu_EmerPowerSapErr    (37)
#define FiMConf_FiMFID_FIM_HvMcu_UartCheckFailErr    (38)
#define FiMConf_FiMFID_FIM_HvMcu_UartLostFrameErr    (39)
#define FiMConf_FiMFID_FIM_HvMcu_UdcCheckErr    (40)
#define FiMConf_FiMFID_FIM_HvMcu_UdcOverVolErr    (41)
#define FiMConf_FiMFID_FIM_HvmcuErr    (42)
#define FiMConf_FiMFID_FIM_IGBTOvTempErr    (43)
#define FiMConf_FiMFID_FIM_IGBTOvTempWarn    (44)
#define FiMConf_FiMFID_FIM_IOHWAB_12VNarrSampErr    (45)
#define FiMConf_FiMFID_FIM_IOHWAB_12VSampErr    (46)
#define FiMConf_FiMFID_FIM_IOHWAB_12VWideSampErr    (47)
#define FiMConf_FiMFID_FIM_IOHWAB_18VLwBrgSampFail    (48)
#define FiMConf_FiMFID_FIM_IOHWAB_18VUpBrgSampFail    (49)
#define FiMConf_FiMFID_FIM_IOHWAB_1V3MCU_SampFail    (50)
#define FiMConf_FiMFID_FIM_IOHWAB_3V3MCU_SampFail    (51)
#define FiMConf_FiMFID_FIM_IOHWAB_5VQcoSampFail    (52)
#define FiMConf_FiMFID_FIM_IOHWAB_5VQt1SampFail    (53)
#define FiMConf_FiMFID_FIM_IOHWAB_5VQt2SampFail    (54)
#define FiMConf_FiMFID_FIM_IOHWAB_Cpld1v8SampFail    (55)
#define FiMConf_FiMFID_FIM_IOHWAB_Cpld3v3SampFail    (56)
#define FiMConf_FiMFID_FIM_IOHWAB_CrashFail    (57)
#define FiMConf_FiMFID_FIM_IOHWAB_DcLnkOverVolFail    (58)
#define FiMConf_FiMFID_FIM_IOHWAB_IphaOCFail    (59)
#define FiMConf_FiMFID_FIM_IOHWAB_KL30OverVolErr    (60)
#define FiMConf_FiMFID_FIM_IOHWAB_KL30SevOverVolFail    (61)
#define FiMConf_FiMFID_FIM_IOHWAB_KL30SevUnderVolFail    (62)
#define FiMConf_FiMFID_FIM_IOHWAB_KL30UnderVolErr    (63)
#define FiMConf_FiMFID_FIM_IOHWAB_Nen33Fail    (64)
#define FiMConf_FiMFID_FIM_IOHWAB_SttrSenorShrFail    (65)
#define FiMConf_FiMFID_FIM_IOHWAB_SttrTemp1SampFail    (66)
#define FiMConf_FiMFID_FIM_IOHWAB_SttrTemp2SampFail    (67)
#define FiMConf_FiMFID_FIM_IOHWAB_TCoolantSampFail    (68)
#define FiMConf_FiMFID_FIM_IOHWAB_VDD5_D_SampFail    (69)
#define FiMConf_FiMFID_FIM_IgbtDrvErr    (70)
#define FiMConf_FiMFID_FIM_IgbtDrv_ComErr    (71)
#define FiMConf_FiMFID_FIM_IgbtDrv_LwBrgFaultAFail    (72)
#define FiMConf_FiMFID_FIM_IgbtDrv_LwBrgFaultBFail    (73)
#define FiMConf_FiMFID_FIM_IgbtDrv_UpBrgFaultAFail    (74)
#define FiMConf_FiMFID_FIM_IgbtDrv_UpBrgFaultBFail    (75)
#define FiMConf_FiMFID_FIM_IohwabSampErr    (76)
#define FiMConf_FiMFID_FIM_Lamp    (77)
#define FiMConf_FiMFID_FIM_LowPowerOvVErr    (78)
#define FiMConf_FiMFID_FIM_LowPowerUnVErr    (79)
#define FiMConf_FiMFID_FIM_MDF_AlOfsNoPlausErr    (80)
#define FiMConf_FiMFID_FIM_MDF_DiashCirNoPsblErr    (81)
#define FiMConf_FiMFID_FIM_MDF_EmacBlkdErr    (82)
#define FiMConf_FiMFID_FIM_MDF_EmacBlkdWarn    (83)
#define FiMConf_FiMFID_FIM_MDF_ICtlRatErr    (84)
#define FiMConf_FiMFID_FIM_MDF_IsOvHiErr    (85)
#define FiMConf_FiMFID_FIM_MDF_OpenCirNoPsblErr    (86)
#define FiMConf_FiMFID_FIM_MDF_OperOutdRngErr    (87)
#define FiMConf_FiMFID_FIM_MDF_PhaseLossFaultErr    (88)
#define FiMConf_FiMFID_FIM_MDF_PrfElDrvErr    (89)
#define FiMConf_FiMFID_FIM_MtrOvTempErr    (90)
#define FiMConf_FiMFID_FIM_MtrOvTempWarn    (91)
#define FiMConf_FiMFID_FIM_PCF_ActOvTiErr    (92)
#define FiMConf_FiMFID_FIM_PCF_IdcOvErr    (93)
#define FiMConf_FiMFID_FIM_PCF_SelfcheckErr    (94)
#define FiMConf_FiMFID_FIM_PCF_SenClbErr    (95)
#define FiMConf_FiMFID_FIM_PCF_SenOvErr    (96)
#define FiMConf_FiMFID_FIM_PCF_StallRetryErr    (97)
#define FiMConf_FiMFID_FIM_PCF_StallWarn    (98)
#define FiMConf_FiMFID_FIM_PCF_UnexpPosErr    (99)
#define FiMConf_FiMFID_FIM_PwrLimLvFour    (100)
#define FiMConf_FiMFID_FIM_PwrLimLvOne    (101)
#define FiMConf_FiMFID_FIM_PwrLimLvThree    (102)
#define FiMConf_FiMFID_FIM_PwrLimLvTwo    (103)
#define FiMConf_FiMFID_FIM_RCF_AccOvTiErr    (104)
#define FiMConf_FiMFID_FIM_RCF_EstOfsErr    (105)
#define FiMConf_FiMFID_FIM_RCF_FwlBwdOvTiErr    (106)
#define FiMConf_FiMFID_FIM_RCF_FwlFwdOvTiErr    (107)
#define FiMConf_FiMFID_FIM_RCF_OfsClbFail    (108)
#define FiMConf_FiMFID_FIM_RCF_PsiOvErr    (109)
#define FiMConf_FiMFID_FIM_RSL_DOSErr    (110)
#define FiMConf_FiMFID_FIM_RSL_ExcErr    (111)
#define FiMConf_FiMFID_FIM_RSL_LOSErr    (112)
#define FiMConf_FiMFID_FIM_RSL_LOTErr    (113)
#define FiMConf_FiMFID_FIM_ReqFailrMod    (114)
#define FiMConf_FiMFID_FIM_RslvOpen    (115)
#define FiMConf_FiMFID_FIM_SCF_DisChgOvTiFail    (116)
#define FiMConf_FiMFID_FIM_SCF_LowPwrShtDwnOvTiFail    (117)
#define FiMConf_FiMFID_FIM_SCF_RunToDischarErr    (118)
#define FiMConf_FiMFID_FIM_SpdOvHiErr    (119)
#define FiMConf_FiMFID_FIM_SpdOvHiWarn    (120)
#define FiMConf_FiMFID_FIM_Sttr1Err    (121)
#define FiMConf_FiMFID_FIM_Sttr2Err    (122)
#define FiMConf_FiMFID_FIM_TPC_SpdOvHiLimFail    (123)
#define FiMConf_FiMFID_FIM_TPC_SpdOvHiWarn    (124)
#define FiMConf_FiMFID_FIM_TPC_TCoolantOvHiWarn    (125)
#define FiMConf_FiMFID_FIM_TPC_TDbcOvHiWarn    (126)
#define FiMConf_FiMFID_FIM_TPC_TDbcOvLoWarn    (127)
#define FiMConf_FiMFID_FIM_TPC_TDbcUHiLimFail    (128)
#define FiMConf_FiMFID_FIM_TPC_TDbcULoLimFail    (129)
#define FiMConf_FiMFID_FIM_TPC_TDbcVHiLimFail    (130)
#define FiMConf_FiMFID_FIM_TPC_TDbcVLoLimFail    (131)
#define FiMConf_FiMFID_FIM_TPC_TDbcWHiLimFail    (132)
#define FiMConf_FiMFID_FIM_TPC_TDbcWLoLimFail    (133)
#define FiMConf_FiMFID_FIM_TPC_TDrvBoardOvHiWarn    (134)
#define FiMConf_FiMFID_FIM_TPC_TIGBTOvHiLimErr    (135)
#define FiMConf_FiMFID_FIM_TPC_TIGBTOvHiWarn    (136)
#define FiMConf_FiMFID_FIM_TPC_TIGBTOvLoWarn    (137)
#define FiMConf_FiMFID_FIM_TPC_TSttrOvHiLimFail    (138)
#define FiMConf_FiMFID_FIM_TPC_TSttrOvHiWarn    (139)
#define FiMConf_FiMFID_FIM_TPC_TSttrOvLoWarn    (140)
#define FiMConf_FiMFID_FIM_TPC_iDcLnkOvCLimFail    (141)
#define FiMConf_FiMFID_FIM_TPC_iDcLnkOvcWarn    (142)
#define FiMConf_FiMFID_FIM_TPC_uDcLnkOvVLimFail    (143)
#define FiMConf_FiMFID_FIM_TPC_uDcLnkOvWarn    (144)
#define FiMConf_FiMFID_FIM_TPC_uDcLnkUnVLimFail    (145)
#define FiMConf_FiMFID_FIM_TPC_uDcLnkUnvWarn    (146)
#define FiMConf_FiMFID_FIM_TrqLimLvFour    (147)
#define FiMConf_FiMFID_FIM_TrqLimLvOne    (148)
#define FiMConf_FiMFID_FIM_TrqLimLvThree    (149)
#define FiMConf_FiMFID_FIM_TrqLimLvTwo    (150)
#define FiMConf_FiMFID_FIM_Unused    (151)
#define FiMConf_FiMFID_FIM_VCUComTimeOut    (152)
#define FiMConf_FiMFID_FIM_flgDchaFailr    (153)
#define FiMConf_FiMFID_FIM_flgFaultLvFive    (154)
#define FiMConf_FiMFID_FIM_flgFaultLvFour    (155)
#define FiMConf_FiMFID_FIM_iDcLnkOvcErr    (156)
#define FiMConf_FiMFID_FIM_iDcLnkOvcWarn    (157)
#define FiMConf_FiMFID_FIM_uDcLnkOvErr    (158)
#define FiMConf_FiMFID_FIM_uDcLnkOvWarn    (159)
#define FiMConf_FiMFID_FIM_uDcLnkUnvErr    (160)
#define FiMConf_FiMFID_FIM_uDcLnkUnvWarn    (161)
#define FiMConf_FiMFID_FiM_FlagforFR    (162)

#define FIM_CFG_NUMBEROFFIDS  (162)
#define FIM_CFG_INVALIDFID  (0)

#endif /* include protection */
